#version 450

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

layout(std430) buffer Out {
	int data[];
};

void main() {
	uint index = gl_LocalInvocationIndex + 4*4*4*(gl_WorkGroupID .x + gl_WorkGroupID .y*8 + gl_WorkGroupID .z*8*8);
	int value = int(index);

	if (index % 2 == 0) {
		value *= 2;
	}

	barrier();

	if (index < 1024*1024) {
		value = 1;
	}
	for (int i = 0; i < 4; i++) {
		if (index % 2 == 0) {
			value += 1;
		}

		barrier();
	}

	barrier();

	data[index] = value;
}